### PR TITLE
moved dataset folder out of src directory

### LINKED ISSUE #8: Organizing Vulnerability Detection Datasets into CSV Format for Improved Analysis
The vulnerability checks (to detect brute force attacks, validate inputs, identify insecure authentication, and analyze security headers) use a Naive Bayes Classifier, and the datasets for classification are stored in separate files. Each dataset consists of an array where 'code' contains a sample code snippet, and 'label' indicates whether the code is vulnerable (1) or not (0).

```
const dataset: DatasetSample[] = [
{
        'code': `const authLimiter = rateLimit({
            windowMs: 15 * 60 * 1000, // 15 minutes
            max: 5, // Limit each IP to 5 requests per windowMs
            message: 'Too many login attempts from this IP, please try again later.'
          });`,
        'label': 0
},
{
        'code': `app.get('/search', (req, res) => {
          const searchQuery = req.query.query;
          const sqlQuery = "SELECT * FROM products WHERE name LIKE %{searchQuery}";
          db.query(sqlQuery, (err, result) => {
            if (err) {
              res.status(500).send('Error executing the query');
            } else {
              res.json(result);
            }
          });
        });
        `,
        'label': 1,
}
]
```

To enhance navigation and analysis, we want to store these datasets in a CSV file format. This would allow for easier handling and organization of the data.

Files may be referred/altered for this change:

1. DetectBruteForceAttack.ts
2. DetectInputValidation.ts
3. InsecureAuthentication.ts
4. AnalyzeSecurityHeaders.ts

**Make sure the end user/developer (who downloads the NPM package) is able to smoothly run the NPM package after these changes.**

### PR DESCRIPTION
**Pull request by shashi-sah2003**
Fixes #8 
I have moved the dataset folder out of the src directory and tested the code
It's working correctly.

### CODE REVIEW

**Comment by prayas7102** [comment]
> Fixes #8 I have moved the dataset folder out of the src directory and tested the code It's working correctly.

i dont want any changes to these files: 
image
 kindly revert it

**Comment by shashi-sah2003** [comment]
@prayas7102 if I wouldn't make the specific changes to these files then the code will break and won't be able to test and generate log pdf.

Do you still want me to keep your changes only without incorporating mine in all the .ts file?

**Comment by shashi-sah2003** [comment]
@prayas7102 if I wouldn't make the specific changes to these files then the code will break and won't be able to test and generate log pdf.

Do you still want me to keep your changes only without incorporating mine in all the .ts file?

**Comment by prayas7102** [comment]
> @prayas7102 if I wouldn't make the specific changes to these files then the code will break and won't be able to test and generate log pdf.
> 
> Do you still want me to keep your changes only without incorporating mine in all the .ts file?

Yes.

**Comment by shashi-sah2003** [comment]
@prayas7102 I have reverted back the changes in the respective .ts files

**Review by prayas7102 — APPROVED** [review]

**Pull request merged**
