### PR TITLE
parses the whole data from csv file directly

### LINKED ISSUE #8: Organizing Vulnerability Detection Datasets into CSV Format for Improved Analysis
The vulnerability checks (to detect brute force attacks, validate inputs, identify insecure authentication, and analyze security headers) use a Naive Bayes Classifier, and the datasets for classification are stored in separate files. Each dataset consists of an array where 'code' contains a sample code snippet, and 'label' indicates whether the code is vulnerable (1) or not (0).

```
const dataset: DatasetSample[] = [
{
        'code': `const authLimiter = rateLimit({
            windowMs: 15 * 60 * 1000, // 15 minutes
            max: 5, // Limit each IP to 5 requests per windowMs
            message: 'Too many login attempts from this IP, please try again later.'
          });`,
        'label': 0
},
{
        'code': `app.get('/search', (req, res) => {
          const searchQuery = req.query.query;
          const sqlQuery = "SELECT * FROM products WHERE name LIKE %{searchQuery}";
          db.query(sqlQuery, (err, result) => {
            if (err) {
              res.status(500).send('Error executing the query');
            } else {
              res.json(result);
            }
          });
        });
        `,
        'label': 1,
}
]
```

To enhance navigation and analysis, we want to store these datasets in a CSV file format. This would allow for easier handling and organization of the data.

Files may be referred/altered for this change:

1. DetectBruteForceAttack.ts
2. DetectInputValidation.ts
3. InsecureAuthentication.ts
4. AnalyzeSecurityHeaders.ts

**Make sure the end user/developer (who downloads the NPM package) is able to smoothly run the NPM package after these changes.**

### PR DESCRIPTION
**Pull request by shashi-sah2003**
Fixes #8 
This is the fresh PR as requested by @prayas7102 
I have tested it on my local machine it's working and generated exact same log file provided by you
let me know if you face any problem
thanks

### CODE REVIEW

**Comment by prayas7102** [comment]
> Fixes #8 This is the fresh PR as requested by @prayas7102 I have tested it on my local machine it's working and generated exact same log file provided by you let me know if you face any problem thanks

@shashi-sah2003 there are some conflicts in your code. https://github.com/prayas7102/NodejsSecurify/pull/18/conflicts

@eleensmathew it would be very helpful if u could take a fresh pull of this PR and check/upload the .pdf or .log file after running the code.

**Comment by shashi-sah2003** [comment]
@prayas7102 I have resolved the conflict it can try it again
The conflict was due to the changes in the main branch on one line in detectBruteForceAttack.ts which you have committed but parse-csv branch has previous version of changes on that line.

**Comment by prayas7102** [comment]
> @prayas7102 I have resolved the conflict, you can try it again The conflict was due to the changes in the main branch on one line in detectBruteForceAttack.ts which you have committed but parse-csv branch has previous version of changes on that line.

@shashi-sah2003 for time being we have decided that we would keep the csv datasets in a separate folder outside src along with other utility script files you've written like: parsingCSVData.ts etc. We would use this csv for training a model separately. So please exclude all other files apart from parsingCSVData.ts & csv files in datasets folder and push a commit for merge.

image

**Comment by shashi-sah2003** [comment]
@prayas7102 I have moved datasets outside the src directory
Now the structure looks like
-datasets
-src
and inside datasets I have added all the csv files and parsingCSVdata.ts files also. But I am facing error while trying to testing
I have attached the pdf generated of error
[NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17416681/NodeJsSecurifyReport.pdf)

pls look into this issue

Even though changing the path in all the respective .ts files it is causing the error and it's looking only inside the src directory for datasets directory for all the csv files and I think you need to modify NodeJsSecurify.ts file to handle this

**Comment by lloydlobo** [comment]
> @prayas7102 I have moved datasets outside the src directory Now the structure looks like -datasets -src and inside datasets I have added all the csv files and parsingCSVdata.ts files also. But I am facing error while trying to testing I have attached the pdf generated of error [NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17416681/NodeJsSecurifyReport.pdf)
> 
> pls look into this issue
> 
> Even though changing the path in all the respective .ts files it is causing the error and it's looking only inside the src directory for datasets directory for all the csv files and I think you need to modify NodeJsSecurify.ts file to handle this

Seems like a path error:
```
Error: ENOENT: no such file or directory, open 'src/datasets/
bruteForceDataset.csv'
 at readFileSync (node:fs:448:20)
```

This required the full path to the csv data. And so instead of hard-coding the absolute path, you could try something like:

```js
path.join(path.resolve(). "src/datasets/bruteForceDataset.csv")
```

OR

```js
path.join(__dirname, "src/datasets/bruteForceDataset.csv")
```

**Comment by shashi-sah2003** [comment]
> > @prayas7102 I have moved datasets outside the src directory Now the structure looks like -datasets -src and inside datasets I have added all the csv files and parsingCSVdata.ts files also. But I am facing error while trying to testing I have attached the pdf generated of error [NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17416681/NodeJsSecurifyReport.pdf)
> > pls look into this issue
> > Even though changing the path in all the respective .ts files it is causing the error and it's looking only inside the src directory for datasets directory for all the csv files and I think you need to modify NodeJsSecurify.ts file to handle this
> 
> Seems like a path error:
> 
> ```
> Error: ENOENT: no such file or directory, open 'src/datasets/
> bruteForceDataset.csv'
>  at readFileSync (node:fs:448:20)
> ```
> 
> This required the full path to the csv data. And so instead of hard-coding the absolute path, you could try something like:
> 
> ```js
> path.join(path.resolve(). "src/datasets/bruteForceDataset.csv")
> ```
> 
> OR
> 
> ```js
> path.join(__dirname, "src/datasets/bruteForceDataset.csv")
> ```
> 
> And similarly tweaking `__dirname` or other paths via path.resolve() in NodeJsSecurify.js Could help with this issue. Can't be so sure without testing it out in person.

@lloydlobo the code is working fine provided the datasets directory is inside src directory but as requested by @prayas7102 when trying to keep datasets directory outside the src directory the above error is encountered. let me know if we can connect sometime to resolve this issue?

**Comment by lloydlobo** [comment]
> > > @prayas7102 I have moved datasets outside the src directory Now the structure looks like -datasets -src and inside datasets I have added all the csv files and parsingCSVdata.ts files also. But I am facing error while trying to testing I have attached the pdf generated of error [NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17416681/NodeJsSecurifyReport.pdf)
> > > pls look into this issue
> > > Even though changing the path in all the respective .ts files it is causing the error and it's looking only inside the src directory for datasets directory for all the csv files and I think you need to modify NodeJsSecurify.ts file to handle this
> > 
> > 
> > Seems like a path error:
> > ```
> > Error: ENOENT: no such file or directory, open 'src/datasets/
> > bruteForceDataset.csv'
> >  at readFileSync (node:fs:448:20)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This required the full path to the csv data. And so instead of hard-coding the absolute path, you could try something like:
> > ```js
> > path.join(path.resolve(). "src/datasets/bruteForceDataset.csv")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OR
> > ```js
> > path.join(__dirname, "src/datasets/bruteForceDataset.csv")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And similarly tweaking `__dirname` or other paths via path.resolve() in NodeJsSecurify.js Could help with this issue. Can't be so sure without testing it out in person.
> 
> @lloydlobo the code is working fine provided the datasets directory is inside src directory but as requested by @prayas7102 when trying to keep datasets directory outside the src directory the above error is encountered. let me know if we can connect sometime to resolve this issue?

It worked when I tried this (also moved it out of src/ into the project directory):

```js
const csv_data = readFileSync(path.join(path.resolve(),"datasets/securityHeadersDataset.csv"), { encoding: "utf8" });
```

Even so, the csv parser will be used for training the data, and not directly. But it'll be great to know that it works either way.

**Comment by shashi-sah2003** [comment]
Thanks for the help @lloydlobo now it's working on my end too but there is a small change 
The ./dist directory created is a bit different than before and now to test the code we have to use

In 1st terminal
npm run start

In 2nd terminal
node ./dist/src/NodeJsSecurify.js ( as NodeJsSecurify.js in created inside this folder)

I am also attaching the log pdf @prayas7102 please verify this and let me know if that's okay so that I can continue with committing the changes

[NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17421286/NodeJsSecurifyReport.pdf)

**Comment by prayas7102** [comment]
> Thanks for the help @lloydlobo now it's working on my end too but there is a small change The ./dist directory created is a bit different than before and now to test the code we have to use
> 
> In 1st terminal npm run start
> 
> In 2nd terminal node ./dist/src/NodeJsSecurify.js ( as NodeJsSecurify.js in created inside this folder) (previously we were using node ./dist/NodeJsSecurify.js)
> 
> I am also attaching the log pdf @prayas7102 please verify this and let me know if that's okay so that I can continue with committing the changes
> 
> [NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17421286/NodeJsSecurifyReport.pdf)

I think you need to resolve conflicts first before testing. https://github.com/prayas7102/NodejsSecurify/pull/18/conflicts
There have been PRs merged after you made this PR.

**Comment by shashi-sah2003** [comment]
@prayas7102 I am using latest pull from the main branch and was working on it
I was going through all the *.ts file and understood one thing that you are trying to export dataset variable from all the .ts file to Vulnerability.ts. 
I managed to resolve that part but while testing I received the following error
[NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17428981/NodeJsSecurifyReport.pdf)

pls look into this, I think this is originating from NodejsSecurify/dist/src/GenerateReport.d.ts and NodejsSecurify/dist/src/NodeJsSecurify.d.ts which also explain that it is coming from NodejsSecurify/src/GenerateReport.ts and NodejsSecurify/src/NodeJsSecurify.ts

**Comment by prayas7102** [comment]
> @prayas7102 I am using latest pull from the main branch and was working on it I was going through all the *.ts file and understood one thing that you are trying to export dataset variable from all the .ts file to Vulnerability.ts. I managed to resolve that part but while testing I received the following error [NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17428981/NodeJsSecurifyReport.pdf)
> 
> pls look into this, I think this is originating from NodejsSecurify/dist/src/GenerateReport.d.ts and NodejsSecurify/dist/src/NodeJsSecurify.d.ts which also explain that it is coming from NodejsSecurify/src/GenerateReport.ts and NodejsSecurify/src/NodeJsSecurify.ts

please change the mode in line 33 (NodeJsSecurify.ts) to DEV before testing.

**Comment by shashi-sah2003** [comment]
@prayas7102 pls review this PR https://github.com/prayas7102/NodejsSecurify/pull/21
I have done the necessary changes

**Pull request closed without merging**
