### PR TITLE
Consolidate common logic for detecting vulnerability

### LINKED ISSUE #7: Unifying Vulnerability Detection with a Single Automated Script for Multiple Security Checks
You can consolidate the four files (`DetectBruteForceAttack.ts`, `DetectInputValidation.ts`, `InsecureAuthentication.ts`, and `AnalyzeSecurityHeaders.ts`) into a single script since they share common libraries and calling functions. The only variation between these files is the dataset, which can be loaded based on the specific vulnerability check being performed.

By creating a single script, you can automate the detection of brute force attacks, input validation, insecure authentication, and security header analysis. This script can selectively load the appropriate dataset according to the type of vulnerability being checked, making the process more efficient and reducing code duplication.

### Key steps:
1. **Unify common logic**: Merge the shared libraries, calling functions, and processes.
2. **Parameterize dataset selection**: Add functionality to the script that chooses the dataset based on the type of vulnerability (brute force, input validation, insecure authentication, security headers).
3. **Call specific checks**: Based on the selected vulnerability type, load the respective dataset and apply the detection logic.

This approach simplifies the process and ensures scalability when adding new vulnerability checks in the future.

**Make sure the end user/developer (who downloads the NPM package) is able to smoothly run the NPM package after these changes.**

### PR DESCRIPTION
**Pull request by lloydlobo**
## Overview

In this PR we consolidate the logic for vulnerability detection by using a map/table to orchestrate detection handling─based on the vulnerability type. 

This approach prioritizes performance (though not tested yet), but it requires careful handling of unknown vulnerabilities.

Closes #7

## Rationale

Instead of using the good old `switch` to handle dynamic data transformation and dispatch, we focus on table lookup on predefined data. 
While this possibly improves (not tested) runtime efficiency by minimizing function calls and string operations, it demands extra caution with unknown vulnerability types. 
And so, we knowingly choose to accept these trade-offs for the sake of performance.

## Changes

- Removes the previous implementation of vulnerability detection from four files, and handle it using consolidated `Vulnerability` enumerations and a unified detection system.
- Adds success and failure logging messages for each enumeration field, that is prepared in advance to avoid string concatenation.

## Resolved potential Bugs

- Resolves a double logging issue when the new detection implementation is declared outside the `Log` class. The function now resides in `Vulnerability.ts`, which appears to have resolved the bug.
  - However, we still need to address the strange logging behavior that might be linked to:
    - Temporary usage of `await` during parsing, should `await` be applied.
    - Overriding `console.log` and `console.error` in `Log` class.

## Future improvements

- [x] Remove the placeholder variable `vulnLabel` in `detectVeulnerability` function if the current table-based logging works well.
- [x] Optionally, review `DatasetSample` interface and their related datasets for greater clarity.
- [x] Add more integration/unit tests that check how we handle different vulnerability types.
  ~~although a basic sanity check already exists in src/Vulnerability/Vulnerability.ts.~~
- [x] Reintroduce basic tests for `Vulnerability` in dedicated file.
- [x] Remove older export declaration of `DatasetSample` from files covered by `Vulnerability` enum.
- Clarify whether the caller or callee should handle logging of new lines (i.e. the linefeed character `\n`.)
- Review exports and imports to ensure consistency with project conventions.
- Introduce basic tests for CSV parsed dataset, when implemented.

### CODE REVIEW

**Comment by prayas7102** [comment]
@lloydlobo thankyou for these awesome changes. I've added you as a collaborator, please accept the invite. If you have any more ideas, I'd be thrilled to see them in the future. Thanks again! 😊

Coming to your changes, I think it would be better if we get this PR #14 merged first. This PR deals with converting all datasets from array to csv and requiring csv directly for prediction purpose. After this gets merged u can include your common logic with it.

For future improvements suggested by you, we can make new issues shortly after this PR and #14 gets merged.

**Comment by lloydlobo** [comment]
> @lloydlobo thankyou for these awesome changes. I've added you as a collaborator, please accept the invite. If you have any more ideas, I'd be thrilled to see them in the future. Thanks again! 😊
> 
> Coming to your changes, I think it would be better if we get this PR #14 merged first. This PR deals with converting all datasets from array to csv and requiring csv directly for prediction purpose. After this gets merged u can include your common logic with it.
> 
> For future improvements suggested by you, we can make new issues shortly after this PR and #14 gets merged.

@prayas7102 Sure thing and thanks :smile:, I am truly honored by the gesture. Already had few ideas pop out while navigating through the codebase. Will be exciting to see how it works out!

Yeah it makes sense and seems to unify the common shape of sample corpus. 

Looking forward to it :)

**Comment by prayas7102** [comment]
@lloydlobo can u make a separate .ts file for this interface, which is getting used everywhere:

export interface DatasetSample {
    code: string;
    label: number;
}

**Review by lloydlobo — COMMENTED** [review]
Merged to resolve conflicts with branch `main`.

**Comment by prayas7102** [comment]
@lloydlobo i was thinking to drop the idea of parsing csv for real time vulnerability detection, instead we can collect the csv datasets with all the utility scripts into a single folder which would be used in model training purpose. After the model is ready we can use it without requiring extra scripts.

**Comment by lloydlobo** [comment]
> @lloydlobo i was thinking to drop the idea of parsing csv for real time vulnerability detection, instead we can collect the csv datasets with all the utility scripts into a single folder which would be used in model training purpose. After the model is ready we can use it without requiring extra scripts.

If that is so then I can add a final commit to sort out the imports/exports. Are we clear that the individual vulnerability files still export the dataset as JS object?

**Comment by prayas7102** [comment]
> > @lloydlobo i was thinking to drop the idea of parsing csv for real time vulnerability detection, instead we can collect the csv datasets with all the utility scripts into a single folder which would be used in model training purpose. After the model is ready we can use it without requiring extra scripts.
> 
> If that is so then I can add a final commit to sort out the imports/exports. Are we clear that the individual vulnerability files still export the dataset as JS object?

yes sure.

**Review by prayas7102 — APPROVED** [review]
All changes looks good !

**Pull request merged**
