### PR TITLE
added pdf functionality

### LINKED ISSUE #10: Enhancing User Experience by Generating Security Audit Reports in PDF, DOC, or TXT Formats
Currently, the output of the NPM package is displayed in the VSCode terminal after running the required commands. However, for end users and developers (who downloads the NPM package), it would be more convenient if the security audit report could be generated as a PDF, DOC, or TXT file, allowing for easier review and avoiding the need to scroll through the terminal output.

Sample terminal report: 
[audit report.pdf](https://github.com/user-attachments/files/17230062/audit.report.pdf)

**Make sure the end user/developer (who downloads the NPM package) is able to smoothly run the NPM package after these changes.**

### PR DESCRIPTION
**Pull request by eleensmathew**
[NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17261699/NodeJsSecurifyReport.pdf)
Added functionality for pdf generation based on console output. Sample pdf attached. Fixes #10

### CODE REVIEW

**Comment by prayas7102** [comment]
> [NodeJsSecurifyReport.pdf](https://github.com/user-attachments/files/17261699/NodeJsSecurifyReport.pdf) Added functionality for pdf generation based on console output. Sample pdf attached. Fixes #10

Thanks for the changes @eleensmathew, however I've minor changes to be fixed:
1. Can you remove the extra * from 2nd line.
2. Remove yellow color font from everywhere, replace it with dark red.
3. Make sure the generated pdf is dumped in the root directory.
4. Run the code again with path: /home/eleensmathew/NodejsSecurify/TestFolder and share the updated pdf (after re-checking with above points).

**Comment by eleensmathew** [comment]
What * are you referring to? can you make a comment on the code regarding this? 
If the code is run again then the old pdf gets overwritten and there is no permission issue.

**Comment by eleensmathew** [comment]
Can you also add the hacktoberfest-accepted label to this issue?

**Comment by prayas7102** [comment]
> What * are you referring to? can you make a comment on the code regarding this? If the code is run again then the old pdf gets overwritten and there is no permission issue.

I was talking about this ***
image

**Comment by prayas7102** [comment]
Thank you so much for your contribution, @eleensmathew ! 🙌
I've added you as a collaborator, please accept the invite.
If you have any more ideas or contributions, I'd be thrilled to see them in the future. Thanks again! 😊

**Review by prayas7102 — APPROVED** [review]

**Pull request merged**
