### PR TITLE
Updated dependencies and convert datasets to CSV

### PR DESCRIPTION
**Pull request by shashi-sah2003**
Fixes Issue #8 
Added support for Vulnerability Detection Datasets into CSV Format for Improved Analysis
All the 4 different csv files are inside src/datasets
CSV-Converter-Utility.ts is the main file that helps to convert given datasets to their specific CSV files.

### CODE REVIEW

**Comment by shashi-sah2003** [comment]
@prayas7102 I have checked with the fresh pull and it's working perfectly fine
pls let me know if there's anything more
thanks
also pls look in the below issue
image

**Comment by shashi-sah2003** [comment]
@prayas7102 I have added the functionality 
- to parse dataset directly from csv file
- removed dataset variable from all above 4 files
- removed src/CSV-Converter-Utility.ts
- removed convertDatasetToCSV(dataset, csvPath);
pls review

**Comment by prayas7102** [comment]
> @prayas7102 I have added the functionality
> 
> * to parse dataset directly from csv file
> * removed dataset variable from all above 4 files
> * removed src/CSV-Converter-Utility.ts
> * removed convertDatasetToCSV(dataset, csvPath);
>   pls review

Remove node-js-securify dependency in package.json and revert back to original version "^1.4.0" for @types/colors dependency also in package.json.

**Comment by prayas7102** [comment]
**From parsingCSVdata.ts:**
Remove calling this function testCSVParser(); line 45.

**For these files: DetectBruteForceAttack.ts, DetectInputValidation.ts, InsecureAuthentication.ts & AnalyzeSecurityHeaders.ts :**
Remove await and use some other technique such that the further code execution doesn't happen until we get a parsed csv, because when using await we're getting erroneous output in log & terminal if u have run the code. 

image

**Comment by shashi-sah2003** [comment]
> @shashi-sah2003
> 
> **Remove `"@types/colors": "^1.4.0"`, from package.json**
> 
> **From parsingCSVdata.ts:** Remove calling this function testCSVParser(); line 45.
> 
> **For these files: DetectBruteForceAttack.ts, DetectInputValidation.ts, InsecureAuthentication.ts & AnalyzeSecurityHeaders.ts :** Remove await and use some other technique such that the further code execution doesn't happen until we get a parsed csv, because when using await we're getting erroneous output in log & terminal (u might know this if u have run the code). This is because if the code execution continues then results from this files gets reported at the very end of terminal output (not at their designated place).
> 
> @lloydlobo maybe u can help him in this part
> 
> image


@prayas7102 I have made following changes
- removed @types/colors": "^1.4.0", from package.json
- modified parsingCSVdata.ts as callback function instead of async function
- modified all the 4 files using callback function so that it doesn't proceed to next line until whole dataset is parsed and it is stored in dataset variable

**Comment by prayas7102** [comment]
> > @shashi-sah2003
> > **Remove `"@types/colors": "^1.4.0"`, from package.json**
> > **From parsingCSVdata.ts:** Remove calling this function testCSVParser(); line 45.
> > **For these files: DetectBruteForceAttack.ts, DetectInputValidation.ts, InsecureAuthentication.ts & AnalyzeSecurityHeaders.ts :** Remove await and use some other technique such that the further code execution doesn't happen until we get a parsed csv, because when using await we're getting erroneous output in log & terminal (u might know this if u have run the code). This is because if the code execution continues then results from this files gets reported at the very end of terminal output (not at their designated place).
> > @lloydlobo maybe u can help him in this part
> > image
> 
> @prayas7102 I have made following changes
> 
> * removed @types/colors": "^1.4.0", from package.json
> * modified parsingCSVdata.ts as callback function instead of async function
> * modified all the 4 files using callback function so that it doesn't proceed to next line until whole dataset is parsed and it is stored in dataset variable

Still the problem is not solved. 

Expected output:

Your Output:

**Comment by prayas7102** [comment]
> > @shashi-sah2003
> > **Remove `"@types/colors": "^1.4.0"`, from package.json**
> > **From parsingCSVdata.ts:** Remove calling this function testCSVParser(); line 45.
> > **For these files: DetectBruteForceAttack.ts, DetectInputValidation.ts, InsecureAuthentication.ts & AnalyzeSecurityHeaders.ts :** Remove await and use some other technique such that the further code execution doesn't happen until we get a parsed csv, because when using await we're getting erroneous output in log & terminal (u might know this if u have run the code). This is because if the code execution continues then results from this files gets reported at the very end of terminal output (not at their designated place).
> > @lloydlobo maybe u can help him in this part
> > image
> 
> @prayas7102 I have made following changes
> 
> * removed @types/colors": "^1.4.0", from package.json
> * modified parsingCSVdata.ts as callback function instead of async function
> * modified all the 4 files using callback function so that it doesn't proceed to next line until whole dataset is parsed and it is stored in dataset variable

Still the issue is not resolved, you can compare expected output and your output. The terminal output from these files still doesn't get reflected in terminal at correct place but at the very end.

Expected Output: 
[NodeJsSecurityReport.log](https://github.com/user-attachments/files/17349909/NodeJsSecurityReport.log)

Your output: 
[NodeJsSecurityReport (1).log](https://github.com/user-attachments/files/17349910/NodeJsSecurityReport.1.log)

**Comment by lloydlobo** [comment]
It seems the nature of asynchronous JS is getting the execution muddled up. Parsing csv to javascript objects first, would be highly preferable, and that too right at the early stage of program execution. 

It will also be a great experiment to not use any csv dependencies. And also avoid promises and async calls, till we get this thing working. If I remember correctly `fs.readFileSync` avoids handling promises or callbacks for reading the file. 

In short, something to try would be: Read all the csv data. Transform each file to a JSON object. And then do the actual logging work.

**Comment by lloydlobo** [comment]
Hacked together a script to test out `fs.readFileSync`.

<details>
<summary>View code</summary>

```javascript
import { assert } from "node:console";
import { readFileSync } from "node:fs"

function parseCSV(csv_data) {
    const [header_line, ...lines] = csv_data.trim().split('\n');
    const headers = header_line.split(',');
    assert(headers.length == 2 && headers[0] == 'code' && headers[1] == 'label');

    const parsed_records = new Array(lines.length);
    let values = ["", 0];
    for (let i = 0; i < lines.length; i += 1) {
        assert(values.length == 2);
        const line = lines[i];
        const last_comma_index = line.lastIndexOf(',');
        const raw_code = line.slice(0, last_comma_index);
        const parsed_code = raw_code.slice(1, -1); // strip surrounding quotes
        assert(parsed_code[0] !== `"` && parsed_code[parsed_code.length - 1] !== `"`);
        const raw_label = line.slice(last_comma_index + 1);
        const parsed_label = parseInt(raw_label, 10);
        assert(!isNaN(parsed_label) && parsed_label >= 0 || parsed_label <= 1);
        values[0] = parsed_code;
        values[1] = parsed_label;

        const record = {}
        for (let j = 0; j < headers.length; j += 1) {
            record[headers[j]] = values[j];
        }
        parsed_records[i] = record;
    }
    assert(parsed_records[parsed_records.length - 1] !== undefined);

    return parsed_records;
}

function testParseCSV() {
    const csv_data = readFileSync("input.csv", { encoding: "utf8" });
    const dataset_sample = parseCSV(csv_data)
    console.log({ dataset_sample });
}

testParseCSV();

```
</details>

**Comment by shashi-sah2003** [comment]
Thank you so much @lloydlobo. Your code is working perfectly fine and producing desired log file
@prayas7102 I have attached the generated log file after testing the changed code and it's giving desired logs
I have committed the changes pls review and let me know if there is any discrepancy
thanks

[NodeJsSecurityReport.log](https://github.com/user-attachments/files/17353321/NodeJsSecurityReport.log)

**Review by prayas7102 — APPROVED** [review]

**Comment by prayas7102** [comment]
@shashi-sah2003 are u sure u have pushed all your last changes? Because on my end it's breaking.

[NodeJsSecurityReport.log](https://github.com/user-attachments/files/17354436/NodeJsSecurityReport.log)

**Comment by prayas7102** [comment]
@shashi-sah2003 make a fresh PR for this issue.

**Comment by shashi-sah2003** [comment]
@prayas7102 I have raised a fresh PR
pls review it

**Pull request merged**
